version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      timezone: America/Sao_Paulo
